# -*- coding: utf-8 -*-
"""dpre

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULBKorc67zSOhLoU1kzdUl8sYsvsVBWn
"""

import pandas as pd
# Load the CSV file
csv_file = "/content/202201-tripdata.csv"
df = pd.read_csv(csv_file)
df

"""Data Cleaning"""

# Count null values
null_count = df.isnull().sum()
null_count

# drop month colum because it has the same val
df = df.drop(columns=["month","Lcation "], axis=1)

# Checking if any NaN is present in column or not
df.isna().any().any()

"""Data Transformation"""

# Perform one-hot encoding for categorical columns
data = pd.get_dummies(df, columns=['rideable_type','member_casual'])
data

from sklearn.preprocessing import MinMaxScaler

# Scale numerical variables using MinMaxScaler
scaler = MinMaxScaler()
df[['trip_length_raw']] = scaler.fit_transform(df[['trip_length_raw']])

"""Data Reduction using Feature Selection"""

import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression

data = pd.read_csv('202201-tripdata.csv')

features = data.drop('trip_length_raw', axis=1)
target = data['trip_length_raw']

features_encoded = pd.get_dummies(features)

k = 5  # Number of features to select
selector = SelectKBest(score_func=f_regression, k=k)
selected_features = selector.fit_transform(features_encoded, target)

selected_indices = selector.get_support(indices=True)
selected_feature_names = features_encoded.columns[selected_indices]

reduced_data = pd.DataFrame(selected_features, columns=selected_feature_names)

# Define the columns you want to create boxplots for
columns_to_plot = [ 'member_casual', 'year', 'rideable_type' ]

# Create individual boxplots for each column
plt.figure(figsize=(15, 10))

for i, column in enumerate(columns_to_plot):
    plt.subplot(3, 4, i + 1)  # Adjust the subplot layout as needed
    sns.boxplot(x=column, y='weekday', data=df, palette="Set2")  # Replace 'your_numerical_column' with the column containing numerical values
    plt.title(f'Boxplot for {column}')
    plt.xlabel(column)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Plot 1: Scatter Plot
plt.figure(figsize=(10, 6))
plt.scatter(df['member_casual'], df['rideable_type'])
plt.title('Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.show()

# Plot 2: Histogram
plt.figure(figsize=(10, 6))
sns.histplot(data['trip_length_raw'], kde=True, color='blue')
plt.title('Histogram')
plt.xlabel('trip_length_raw')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Save the cleaned data to a new CSV file
cleaned_csv_file = "/content/202201-tripdata.csv"
data.to_csv(cleaned_csv_file, index=False)