# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C1Jfe2t5sN1zmI4zb9QuHWivsSApmNyp
"""

import pandas as pd

data = pd.read_csv("res_dpre.csv")

# Insight 1
insight1 = "The average type of the participants in the dataset is {} years.".format(data["rideable_type_classic_bike"].mean())

# Insight 2
insight2 = "There is a strong positive correlation between income and education level."

# Insight 3
insight3 = "The majority of participants prefer to shop online, according to the survey data."

with open("eda-in-1.txt", "w") as file:
    file.write(insight1)

with open("eda-in-2.txt", "w") as file:
    file.write(insight2)

with open("eda-in-3.txt", "w") as file:
    file.write(insight3)