# -*- coding: utf-8 -*-
"""model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-Hizc8pcVMMIeHIcFZui8Hbmch3NYCj
"""

import pandas as pd
from sklearn.cluster import KMeans
import numpy as np

df = pd.read_csv('/content/202201-tripdata.csv')


# Define the number of clusters (k=3)
k = 3

# Initialize and fit the K-means model
kmeans = KMeans(n_clusters=k)
kmeans.fit(df)

# Get the cluster assignments for each data point
cluster_assignments = kmeans.labels_

# Count the number of records in each cluster
cluster_counts = [0] * k
for label in cluster_assignments:
    cluster_counts[label] += 1

# Save the cluster counts to a text file
with open(f'{k}.txt', 'w') as file:
    for cluster, count in enumerate(cluster_counts):
        file.write(f'Cluster {cluster}: {count} records\n')