# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5YAcQjSgPeI2PSyDMStaUHCCcpfz687
"""

import pandas as pd
from sklearn.cluster import KMeans

data = pd.read_csv("res_dpre.csv")
# Select suitable columns for K-means
selected_columns = data[['rideable_type_classic_bike', 'rideable_type_electric_bike', 'member_casual_member']]

kmeans = KMeans(n_clusters=3)
kmeans.fit(selected_columns)

labels = kmeans.labels_

cluster_counts = pd.Series(labels).value_counts()

cluster_counts.to_csv('k.txt', header=False, sep='\t')