# -*- coding: utf-8 -*-
"""vis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12NTW9ebyeby2u9V7_Xo-P4P_D7Eas4ZJ
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sys
import subprocess


# Import data
df = pd.read_csv('/content/202201-tripdata.csv')

categorical_column = 'rideable_type'
numerical_column = 'trip_length_raw'
# Create a box plot to visualize the relationship
plt.figure(figsize=(10, 6))
sns.boxplot(x=categorical_column, y=numerical_column, data=df, palette='Set2')
plt.title(f'Box Plot: {categorical_column} vs. {numerical_column}')
plt.xlabel(categorical_column)
plt.ylabel(numerical_column)
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.grid(True)

# Save the figure
plt.savefig('vis.png', bbox_inches='tight')